boot.o: boot.S multiboot.h x86_desc.h types.h
exceptions.o: exceptions.S
init_paging.o: init_paging.S
x86_desc.o: x86_desc.S x86_desc.h types.h
exception_handler.o: exception_handler.c exception_handler.h lib.h \
  types.h
filesys.o: filesys.c filesys.h lib.h types.h
i8259.o: i8259.c i8259.h types.h lib.h
idt.o: idt.c idt.h x86_desc.h types.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h i8259.h debug.h \
  tests.h idt.h keyboard.h rtc.h filesys.h paging.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h lib.h
lib.o: lib.c lib.h types.h
paging.o: paging.c paging.h types.h lib.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h
terminal.o: terminal.c terminal.h keyboard.h types.h i8259.h lib.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h i8259.h \
  rtc.h terminal.h filesys.h
